// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_webDev_store.Data;

#nullable disable

namespace dotnet_webDev_store.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230808184040_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnet_webDev_store.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Valerio De Sanctis",
                            BookTitle = "ASP.NET Core 3 and Angular 9",
                            DateAdded = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learning full stack development calls for knowledge of both frontend and backend web development. By covering the impressive capabilities of ASP.NET Core 3.1 and Angular 9, right from project setup through to the deployment phase, this book will help you to develop your skills effectively.",
                            Price = 265.99m,
                            Rating = 5
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Mircea Teodor Oprea",
                            BookTitle = "Full-stack ASP.NET Core: Build full-stack web applications",
                            DateAdded = new DateTime(2020, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn how to build full-stack web applications using the latest ASP.NET Core technologies. The book follows the development of a real-life small project, so you are sure to have a fully functional project by the end.",
                            Price = 50.00m,
                            Rating = 1
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Mark J. Price",
                            BookTitle = "C# 8.0 and .NET Core 3.0 - Modern Cross-Platform Development",
                            DateAdded = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In C# 8.0 and .NET Core 3.0 – Modern Cross-Platform Development, Fourth Edition, expert teacher Mark J. Price gives you everything you need to start programming C# applications. This latest edition uses the popular Visual Studio Code editor to work across all major operating systems. It is fully updated and expanded with new chapters on Content Management Systems (CMS) and machine learning with ML.NET.",
                            Price = 195.00m,
                            Rating = 4
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Antonio Esposito",
                            BookTitle = "Reactive Programming for .NET Developers",
                            DateAdded = new DateTime(2016, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reactive programming is an innovative programming paradigm focused on time-based problem solving. It makes your programs better-performing, easier to scale, and more reliable. Want to create fast - running applications to handle complex logics and huge datasets for financial and big - data challenges? Then you have picked up the right book!",
                            Price = 257.50m,
                            Rating = 2
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Sam Ruby",
                            BookTitle = "Agile Web Development with Rails 6",
                            DateAdded = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn Rails the way the Rails core team recommends it, along with the tens of thousands of developers who have used this broad tutorial and reference. If you're new to Rails, you'll get step-by-step guidance. If you're an experienced developer, get the comprehensive information you need for the latest version of Ruby on Rails. The new edition of this award-winning classic is completely updated for Rails 6 and Ruby 2.6, with information on system testing, Webpack, and advanced JavaScript.",
                            Price = 538.00m,
                            Rating = 3
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Leonard Base",
                            BookTitle = "JavaScript for Beginners",
                            DateAdded = new DateTime(2020, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This book provides a comprehensive description of the basic JavaScript language and brings new chapters documenting server-side jQuery and JavaScript. Recommended for programmers who want to learn web programming language and for JavaScript programmers who want to broaden their knowledge and master the language. This is the complete and definitive JavaScript programmer's guide and reference manual.",
                            Price = 160.00m,
                            Rating = 5
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Max Beerbohm",
                            BookTitle = "TypeScript: The Ultimate Beginners Guide",
                            DateAdded = new DateTime(2020, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "TypeScript is a programming language designed for large-scale JavaScript application development, it has been designed as a typed superset of JavaScript. This means we’ve actually been writing TypeScript this whole time! This language allow us to use features from the most recent ECMAScript versions and even some features that are not even in the scope of the standard.",
                            Price = 69.99m,
                            Rating = 1
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Greg Sidelnikov",
                            BookTitle = "Node.js API: Learn server-side JavaScript",
                            DateAdded = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn how to build your own vanilla Node.js server from scratch with MySQL database.",
                            Price = 249.00m,
                            Rating = 3
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Frank Zammetti",
                            BookTitle = "Modern Full-stack Development",
                            DateAdded = new DateTime(2020, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore what React, Node, TypeScript, Webpack, and Docker have to offer individually, and how they all fit together in modern app development. You’ll begin by building a solid foundation of knowledge and quickly expand it by constructing two different real-world apps. ",
                            Price = 346.50m,
                            Rating = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
